app/models.py
from app.extensions import db

class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

app/__init__.py
from flask import Flask
from app.config import Config
from app.extensions import db
from app.users.routes import bp
import time
from sqlalchemy.exc import OperationalError

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    app.register_blueprint(bp)

    # with app.app_context():
    #     for _ in range(10):
    #         try:
    #             db.create_all()
    #             break
    #         except Exception:
    #             time.sleep(2)
    with app.app_context():
        retries = 10
        while retries > 0:
            try:
                db.create_all()
                break
            except OperationalError:
                retries -= 1
                time.sleep(2)
    return app

app/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models import User
from app.users.service import (
    get_all_users, create_user, update_user, delete_user
)

bp = Blueprint("users", __name__)

@bp.route("/")
def index():
    users = get_all_users()
    return render_template("index.html", users=users)

@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        create_user(request.form["name"], request.form["email"])
        return redirect(url_for("users.index"))
    return render_template("create.html")

@bp.route("/edit/<int:user_id>", methods=["GET", "POST"])
def edit(user_id):
    user = User.query.get_or_404(user_id)
    if request.method == "POST":
        update_user(user, request.form["name"], request.form["email"])
        return redirect(url_for("users.index"))
    return render_template("edit.html", user=user)

@bp.route("/delete/<int:user_id>")
def delete(user_id):
    user = User.query.get_or_404(user_id)
    delete_user(user)
    return redirect(url_for("users.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Flask CRUD{% endblock %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="bg-gray-100 min-h-screen">
    <nav class="bg-blue-600 p-4 text-white">
      <h1 class="text-xl font-bold text-center">Two Tier Application</h1>
      <h1 class="text-xl font-bold">Flask CRUD</h1>
    </nav>

    <div class="container mx-auto mt-8">{% block content %}{% endblock %}</div>
  </body>
</html>

app/templates/create.html
{% extends "base.html" %} {% block content %}
<form method="POST" class="bg-white p-6 rounded shadow w-1/2">
  <input
    name="name"
    placeholder="Name"
    class="w-full p-2 border mb-4"
    required
  />

  <input
    name="email"
    placeholder="Email"
    class="w-full p-2 border mb-4"
    required
  />

  <button class="bg-blue-600 text-white px-4 py-2 rounded">Save</button>
</form>
{% endblock %}

app/templates/edit.html
{% extends "base.html" %} {% block content %}
<form method="POST" class="bg-white p-6 rounded shadow w-1/2">
  <input name="name" value="{{ user.name }}" class="w-full p-2 border mb-4" />

  <input name="email" value="{{ user.email }}" class="w-full p-2 border mb-4" />

  <button class="bg-blue-600 text-white px-4 py-2 rounded">Update</button>
</form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block title %}Users{% endblock %} {% block content
%}
<a
  href="{{url_for('users.create') }}"
  class="bg-green-600 text-white px-4 py-2 rounded"
>
  Add User
</a>

<table class="mt-6 w-full bg-white shadow rounded">
  <thead class="bg-gray-200">
    <tr>
      <th class="p-2">ID</th>
      <th class="p-2">Name</th>
      <th class="p-2">Email</th>
      <th class="p-2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr class="border-t">
      <td class="p-2">{{ user.id }}</td>
      <td class="p-2">{{ user.name }}</td>
      <td class="p-2">{{ user.email }}</td>
      <td class="p-2">
        <a
          href="{{ url_for('users.edit', user_id=user.id) }}"
          class="text-blue-600"
          >Edit</a
        >
        |
        <a
          href="{{ url_for('users.delete', user_id=user.id) }}"
          class="text-red-600"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}